------------------------------------------------------------
-- PRIMARY KEY(기본키)
------------------------------------------------------------

ALTER TABLE "PARTS"
ADD CONSTRAINT "PK_PARTS"
PRIMARY KEY ("part_id");

ALTER TABLE "ESTIMATES"
ADD CONSTRAINT "PK_ESTIMATES"
PRIMARY KEY ("estimated_id");

ALTER TABLE "USERS"
ADD CONSTRAINT "PK_USERS"
PRIMARY KEY ("user_id");

ALTER TABLE "PRICE_HISTORY"
ADD CONSTRAINT "PK_PRICE_HISTORY"
PRIMARY KEY ("price_history_id");

ALTER TABLE "ESTIMATE_ITEMS"
ADD CONSTRAINT "PK_ESTIMATE_ITEMS"
PRIMARY KEY ("item_id");

ALTER TABLE "RESELL_POSTS"
ADD CONSTRAINT "PK_RESELL_POSTS"
PRIMARY KEY ("post_id");

ALTER TABLE "PART_SPECS"
ADD CONSTRAINT "PK_PART_SPECS"
PRIMARY KEY ("spec_id");